name: terraform infra+deploy
on:
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v6
            - name: azure login
              uses: azure/login@v1
              with:
                creds: ${{secrets.AZURE_SECRET}}
            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
            - name: Terraform Init
              working-directory: terraform
              run: terraform init
            - name: Terraform apply
              working-directory: terraform
              run: terraform apply --auto-approve
            - name: Setup .NET
              uses: actions/setup-dotnet@v6
              with:
                dotnet-version: '10.0.x'
            - name: Restore dependencies
              run: |
                cd UrbanCompany/
                dotnet restore
            - name: publish
              run: |
                cd UrbanCompany/
                dotnet publish UrbanCompany.csproj -c Release -o publish
            - name: Deploy to Azure Web App
              uses: azure/webapps-deploy@v2
              with:
                app-name: ucwebapp123
                package: ./UrbanCompany/publish

               
            